name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches-ignore:
      - "main"

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs
      - name: PHPUnit Unit Tests
        uses: php-actions/phpunit@v4
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath gmp xdebug
          testsuite: Unit
          args: --no-coverage
          version: 10.5

  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs
      - name: Prepare DB
        run: |
          mkdir -p $(dirname $GITHUB_WORKSPACE/bitpay.sqlite)
          touch $GITHUB_WORKSPACE/bitpay.sqlite
          php bin/console doctrine:schema:update --force --env=test
      - name: PHPUnit Integration Tests
        uses: php-actions/phpunit@v4
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath gmp xdebug
          testsuite: Integration
          version: 10.5
          args: --no-coverage

  phpcs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath gmp xdebug
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --standard=phpcs.xml.dist
